export const PERSONAL_FINANCE_CATEGORIES = [
  'INCOME',
  'LOAN_DISBURSEMENTS',
  'LOAN_PAYMENTS',
  'TRANSFER_IN',
  'TRANSFER_OUT',
  'BANK_FEES',
  'ENTERTAINMENT',
  'FOOD_AND_DRINK',
  'GENERAL_MERCHANDISE',
  'HOME_IMPROVEMENT',
  'MEDICAL',
  'PERSONAL_CARE',
  'GENERAL_SERVICES',
  'GOVERNMENT_AND_NON_PROFIT',
  'TRANSPORTATION',
  'TRAVEL',
  'RENT_AND_UTILITIES',
  'OTHER',
] as const;

export type PersonalFinanceCategory = typeof PERSONAL_FINANCE_CATEGORIES[number];

export const PERSONAL_FINANCE_CATEGORY_COLORS: Record<PersonalFinanceCategory, string> = {
  INCOME: '#22C55E',
  LOAN_DISBURSEMENTS: '#0EA5E9',
  LOAN_PAYMENTS: '#6D28D9',
  TRANSFER_IN: '#14B8A6',
  TRANSFER_OUT: '#6366F1',
  BANK_FEES: '#A855F7',
  ENTERTAINMENT: '#EF4444',
  FOOD_AND_DRINK: '#8B5CF6',
  GENERAL_MERCHANDISE: '#3B82F6',
  HOME_IMPROVEMENT: '#F59E0B',
  MEDICAL: '#10B981',
  PERSONAL_CARE: '#60A5FA',
  GENERAL_SERVICES: '#06B6D4',
  GOVERNMENT_AND_NON_PROFIT: '#0EA5E9',
  TRANSPORTATION: '#F59E0B',
  TRAVEL: '#10B981',
  RENT_AND_UTILITIES: '#F97316',
  OTHER: '#9CA3AF',
};

export const getCategoryColorFromConstants = (category: string): string => {
  const key = String(category || 'OTHER') as PersonalFinanceCategory;
  return PERSONAL_FINANCE_CATEGORY_COLORS[key] ?? PERSONAL_FINANCE_CATEGORY_COLORS.OTHER;
};
